name: Docker Build Image

on:
  workflow_call:

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - name: simple
        uses: Foxon-Consulting/github-actions/delivery/simple/delivery_step@main
